FROM node:22-alpine AS build

WORKDIR /app

RUN npm install -g pnpm@10.13.1

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm build


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
